# Generated by Django 5.2.10 on 2026-02-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
