# Generated by Django 5.2.10 on 2026-02-28 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_post_tagged_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='connection_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.connectionrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invitation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW', 'New Follower'), ('LIKE', 'Post Like'), ('COMMENT', 'Post Comment'), ('CONNECTION_REQUEST', 'Connection Request'), ('COLLAB_INVITATION', 'Collaboration Invitation'), ('TAG', 'User Tag'), ('ACCEPT_COLLAB', 'Collaboration Accepted'), ('ACCEPT_CONNECTION', 'Connection Accepted')], default='TAG', max_length=30),
        ),
    ]
