# Generated by Django 5.2.10 on 2026-03-05 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_notification_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW', 'New Follower'), ('LIKE', 'Post Like'), ('COMMENT', 'Post Comment'), ('CONNECTION_REQUEST', 'Connection Request'), ('COLLAB_INVITATION', 'Collaboration Invitation'), ('TAG', 'User Tag'), ('ACCEPT_COLLAB', 'Collaboration Accepted'), ('ACCEPT_CONNECTION', 'Connection Accepted'), ('INTERESTED', 'Project Interest')], default='TAG', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
